package com.example.calorietracker.ui

enum class Screens {
    FIRST_SCREEN,
    SECOND_SCREEN,
    THIRD_SCREEN,
    HOME_SCREEN,
    MEAL_ADD_SCREEN,
    ACCOUNT_SCREEN,
    EDIT_PERSONAL_INFO_SCREEN,
    EDIT_BIOMETRIC_INFO_SCREEN,
    EDIT_NUTRITIONAL_INFO_SCREEN
}